# Generated by Django 4.2.5 on 2024-04-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_devicefetch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicefetch',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
