# Generated by Django 4.2.5 on 2024-04-09 10:16

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_deviceregister_devicefetch_dc_devicefetch_mi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicefetch',
            name='method_capture',
        ),
        migrations.AddField(
            model_name='devicefetch',
            name='csc_Id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devicefetch',
            name='id',
            field=models.AutoField(default=builtins.id, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicefetch',
            name='mac',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devicefetch',
            name='purpose',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='devicefetch',
            name='port',
            field=models.TextField(),
        ),
    ]
