# Generated by Django 4.2.5 on 2024-04-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_devicefetch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceauth',
            name='port',
        ),
    ]
