# Generated by Django 4.2.5 on 2024-04-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_devicefetch_csc_id_remove_devicefetch_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicefetch',
            old_name='method_capture',
            new_name='csc_id',
        ),
        migrations.AddField(
            model_name='devicefetch',
            name='device_id',
            field=models.AutoField(default='id', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicefetch',
            name='mac',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devicefetch',
            name='purpose',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='devicefetch',
            name='port',
            field=models.TextField(),
        ),
    ]
