# Generated by Django 4.2.5 on 2024-04-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_method_capture_devicefetch_csc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicefetch',
            name='device_id',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False, verbose_name='Device_ID'),
        ),
    ]
