# Generated by Django 4.2.5 on 2024-04-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_devicefetch_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceauth',
            name='port',
        ),
    ]
